name: careme24
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  flutter_svg_provider:
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  outline_gradient_button: ^2.0.0+1
  intl: ^0.19.0
  getwidget: ^4.0.0
  flutter_advanced_switch:
  image_picker: ^1.0.4
  flutter_masked_text2:
  card_swiper:
  flutter_slidable:
  dotted_border:


  path_provider: ^2.0.11
  permission_handler: ^11.0.1

  camera:

  syncfusion_flutter_sliders: ^25.2.6
  sizer:
  social_media_recorder:
 # media_picker_widget:
  dio: ^5.4.0
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  freezed: ^2.4.6
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.8.0
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0



dev_dependencies: 
  build_runner: ^2.4.8
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/medicine_help.jpeg
    - assets/fire_help.jpeg
    - assets/logo.svg
    - assets/emergency_help_icon.svg
    - assets/emergency_help.jpeg
    - assets/fire_help_icon.svg
    - assets/medicine_help_icon.svg
    - assets/police_help_icon.svg
    - assets/ru_flag.svg
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRomanMedium.ttf
          weight: 500
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/UbuntuMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: AppIconAdmin
      fonts:
        - asset: assets/fonts/AppIconAdmin.ttf
    - family: CarCustom
      fonts:
        - asset: assets/fonts/CarCustom.ttf
